name: packer-hcl

on:
  pull_request:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  SOURCE_AMI: ami-0dfcb1ef8550277af
  ARTIFACT_NAME: ../webapp.zip

jobs:
  build:
    name: packer validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
      # - run: zip -r webapp.zip *.js *.json
      - name: Zip Git Repository
        uses: montudor/action-zip@v1
        with:
          args: zip -r webapp.zip .
          source: .
          destination: .

      - name: Packer Validate
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          # arguments: '-var "source_filename=${{ env.ARTIFACT_NAME }}" -var "aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }}" -var "aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}"'
          target: main.pkr.hcl
          working_directory: ./packer/
