name: packer-hcl

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    name: packer validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip
          unzip packer_1.7.2_linux_amd64.zip
          sudo mv packer /usr/local/bin/

      - name: Zip Git Repository
        uses: montudor/action-zip@v0.2.0
        with:
          args: zip -r webapp.zip .
          source: .
          destination: .

      - name: Build AWS Image using Packer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          SOURCE_AMI: ami-0dfcb1ef8550277af
          ARTIFACT_NAME: webapp.zip
        run: |
          packer validate -var "source_filename=${{ env.ARTIFACT_NAME }}" -var "aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }}" -var "aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}" main.pkr.hcl
          rm webapp.zip