name: packer-hcl

on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  SOURCE_AMI: ami-0dfcb1ef8550277af
  ARTIFACT_NAME: ../webapp.zip

jobs:
  build:
    name: packer build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
      # - run: zip -r webapp.zip *.js *.json
      - name: Zip Git Repository
        uses: montudor/action-zip@v1
        with:
          args: zip -r webapp.zip .
          source: .
          destination: .

      - name: Packer Build
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          # arguments: '-var "source_filename=${{ env.ARTIFACT_NAME }}" -var "aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }}" -var "aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}"'
          target: main.pkr.hcl
          working_directory: ./packer/
      
      - name: Update Launch Template
        if: always() # run even if previous step fails
        run: |
          asg_name="webapp_autoscaling_group"

          # Check if the autoscaling group exists
          asg_exists=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names $asg_name --query "length(AutoScalingGroups)")

          if [ "$asg_exists" -eq 0 ]; then
            echo "Autoscaling group $asg_name not found. Exiting."
            exit 1
          else

          # Get the latest AMI ID
          latest_ami=$(aws ec2 describe-images \
          --owners self \
          --filters "Name=state,Values=available" "Name=architecture,Values=x86_64" "Name=root-device-type,Values=ebs" \
          --query "reverse(sort_by(Images, &CreationDate))[0].ImageId" \
          )
          echo "The latest AMI is: $latest_ami"

          # Update the launch template with the latest AMI
          aws ec2 create-launch-template-version \
          --launch-template-name EC2-CSYE6225 \
          --source-version 1 \
          --launch-template-data '{"ImageId":'$latest_ami'}'

          # Refresh instances in the autoscaling group
          aws autoscaling start-instance-refresh \
          --auto-scaling-group-name $asg_name

          fi